### ISSUE TITLE
Rise of the Tomb Raider Crashes with Comet Turned On

### ISSUE THREAD

**Issue by ProfessorCode212** [imLinguin/comet#80]
**Describe the bug**
In Rise of the Tomb Raider (GOG's version), the game tends to crash whenever you interact with a campsite. It may also crash when you die and the game reloads the last save. This problem doesn't seem to occur if you play it offline or have Comet disabled.

**To Reproduce**
1. Run Rise of the Tomb Raider.
2. Go to a camp site.
3. Interact with it.
4. The game will crash either as it's loading into the camp site menu or as you try to exit the menu.

**System (please complete the following information):**
 - OS: Fedora GNOME
 - Architecture: x86
 - Launcher: Heroic
 - Proton Version: GE-Proton10-latest (or GE-Proton10-20), GE-Proton10-17

**Additional context**
Others have reported the issue here: https://www.gog.com/forum/tomb_raider_series/rise_of_the_tomb_raider_crash_at_campsites.

**Comment by imLinguin** [comment]
Thanks I'll try to reproduce this

**Comment by imLinguin** [comment]
I did reproduce it, I think however this is a game specific problem. I'm open to suggestions or help to narrow it down
but seeing that the game closes the connection on its own
```
[2025-10-19T17:20:55Z INFO  comet::api::handlers::communication_service] Unlocking achievement NEW_ACHIEVEMENT_3_3, Jednostronna rozmowa
[2025-10-19T17:21:05Z INFO  comet::api::handlers] Uploading new achievements
[2025-10-19T17:21:05Z INFO  comet::api::handlers] Uploaded achievements
[2025-10-19T17:23:19Z INFO  comet::api::handlers] Uploading new stats
[2025-10-19T17:23:20Z INFO  comet::api::handlers] Uploaded stats
[2025-10-19T17:24:35Z INFO  comet::api::handlers] Socket connection closed with Some("58668848197088414")
```
hints that this isnt related to communication with comet, but could indicate an issue related with steam_api wrapper or Galaxy libs, I also wouldn't cross out a possibility of it being a Proton specific problem too

**Comment by imLinguin** [comment]
@ProfessorCode212 This is a shot in blind on this issue, but setting `OPENSSL_ia32cap=0x20000000` may show some interesting results

**Comment by fornkatt** [comment]
Hi,

Sorry for just barging in on this closed issue but I am in the middle of a Rise playthrough and encountering this exact same issue and am led to believe it is indeed only happening with Comet enabled. It has been very hard to reproduce and troubleshoot because it doesn't happen every single time I sit at a camp site but it does seem to only happen when I get the line `Socket connection closed with Some("58668848197088414")` in `comet.log` as every single log when it crashed has this at the bottom. This seems to be the game closing the connection causing a crash as outlined above?

The environment variable posted above does not stop the crashes sadly.

I am very willing to help troubleshoot this issue but I also have no real idea on how to narrow it down further.

#### Some additional info about my setup:
* CachyOS KDE
* Proton CachyOS 11.0-20260703
* Heroic Launcher

[comet.log](https://github.com/user-attachments/files/31124578/comet.log)

**Comment by imLinguin** [comment]
It'd be interesting if you could gather Proton log of the game, especially the moment when it crashes. In Heroic make sure to enable verbose logs. 

Few guesses I have
- Bad implementation of GOG SDK (this begs the question if anyone with GOG Galaxy had similar issues)
- Online features that were moved offline are not as stable as they should

**Comment by fornkatt** [comment]
Actually, it so happens that I had verbose logging enabled, I'm guessing it's the `launch.log` that you want to look at? It's pretty big and fails to upload so I'll share it from my drive as I don't want to truncate it in case I accidentally delete something that could have been of use to you. This is from my latest run so the crash moment should be at the bottom.

If there's something wrong with the log or you want me to check something else, just say the word!

When I have the time I could look into getting the game running through official GOG Galaxy on Faugus. I don't have a Windows installation anymore but I wager the issue is not present using the official launcher since there would probably be more comments about it in that case. I would like to test this though.

[launch.log](https://app.filen.io/#/d/af2e6623-42bc-4c26-a3b9-ba2ff3f4dfd3%23454f32325a4577517a576746384c636e6c3465737a64346f32384c785a38394f)

**Comment by imLinguin** [comment]
~~Actually the protonfixes overwrote your env variable, with an invalid value we had since corrected.
Can you run it with `PROTONFIXES_DISABLE=1` as well as your current `OPENSSL_ia32cap` setting?~~

Actually I stand corrected, I provided an invalid value in here `OPENSSL_ia32cap=~0x20000000` is correct - note the `~` sign

**Comment by CommandMC** [comment]
Doesn't seem like Protonfixes does the wrong thing:
```
ProtonFixes[11460] INFO: Adding env: OPENSSL_ia32cap=~0x20000000
```
The `~` here is required (to tell it to use every capability except for one)

**Comment by fornkatt** [comment]
Right, so on that front we were fine and running it again with `~0x20000000` set as the value in Heroic won't really change anything then?

I managed to get the game working on official GOG Galaxy on Faugus so I will try running a longer session through there to see if I can trigger a crash or not. More testing will have to wait a bit though since a session can run for an hour before I can trigger a crash by sitting at a camp site so I need to set aside some time.

**Comment by fornkatt** [comment]
I had a 3 hour gaming session just now on the official GOG Galaxy launcher through Faugus and was able to progress much farther than I was ever allowed to before without encountering a single crash when sitting at a camp site. I visited multiple camp sites in different locations, both new and old collecting a bunch of collectibles and progressing the story. Everything was completely normal whereas it usually crashed within an hour or so but it was variable. It could be that I was lucky this session, but I'm more inclined to believe the official launcher does not have this issue. I'd be interested to know what you think and if there's anything I can do to collect more useful data.

My setup was otherwise exactly the same. Same Proton version, same env variables like Wayland, HDR and DLSS upgrades so the only difference would be the launcher used.

**Update:**
I've now been playing like normal on GOG Galaxy through Faugus for several days and haven't experienced a single crash. I went back to try Heroic again and as expected, it crashes just like before so I'm inclined to believe there is _something_ about Heroic/Comet that the game does not like (I changed the env variable to `OPENSSL_ia32cap=~0x20000000` with the `~` just in case but it likely did nothing since that is what ProtonFixes set anyway). Maybe it was a known issue for the GOG release of the game and Galaxy handles it somehow? Thought I'd post this update. Hopefully this can get figured out so other people who play this game after me won't encounter these crashes.

**Comment by imLinguin** [comment]
This seems to narrow down to Steam wrapper that GOG develops. There is a similar problem with Blood of the Dawnwalker as well. While I'm trying to find the root cause of the problem, I'm not getting very promising results right now. This issue is now tagged help wanted.

**Comment by imLinguin** [comment]
Importing the following registry may fix the problem.

```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\GOG.com\GalaxyClient\paths]
"client"="C:\\Program Files\\GOG Galaxy"
```

The crash with Blood of the Dawnwalker was resolved by it. @fornkatt if you are still interested in the game, any testing of this would be appreciated

**Comment by fornkatt** [comment]
I finished the game a while back but did a few test runs with the registry entry you posted. Sadly the game still crashed after a while when sitting at a camp site.

[comet.log](https://github.com/user-attachments/files/32414799/comet.log)

[launch.log](https://app.filen.io/#/d/c633e819-cd70-4e48-aabc-5de7ff4b09fb%2333494a7763766a764a5f4f2d66323937374d4934395f47744165455244456633)

<img width="1028" height="356" alt="Image" src="https://github.com/user-attachments/assets/ee75add4-9460-4b1a-8051-6bda8e7dcc55" />
